//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "bairro")
public class Bairro implements Serializable {

    @Column(name = "codigo", table = "bairro", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("codigo")
    private Integer codigo;

    @Column(name = "nome", table = "bairro", unique = false, updatable = true, insertable = true, nullable = false, length = 30, scale = 0, precision = 0)
    @Basic
    @FormParam("nome")
    private String nome;

    @ManyToOne(optional = true, targetEntity = Cidade.class)
    @JoinColumn(name = "cod_cidade", insertable = true, nullable = true, unique = false, updatable = true)
    private Cidade codCidade;

    @OneToMany(targetEntity = Endereco.class, mappedBy = "codBairro")
    private List<Endereco> enderecoCollection;

    public Bairro() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Cidade getCodCidade() {
        return this.codCidade;
    }

    public void setCodCidade(Cidade codCidade) {
        this.codCidade = codCidade;
    }

    public List<Endereco> getEnderecoCollection() {
        return this.enderecoCollection;
    }

    public void setEnderecoCollection(List<Endereco> enderecoCollection) {
        this.enderecoCollection = enderecoCollection;
    }
}
