//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "bairro")
public class Bairro implements Serializable {

    @Id
    @SequenceGenerator(name="bairro_codigo_seq", sequenceName="bairro_codigo_seq", allocationSize = 1)
    @GeneratedValue(generator="bairro_codigo_seq", strategy=GenerationType.SEQUENCE)
    private Integer codigo;

    @Column(name = "nome", table = "bairro", nullable = false, length = 30)
    @Basic
    private String nome;

    @ManyToOne(targetEntity = Cidade.class)
    @JoinColumn(name = "cod_cidade")
    private Cidade cidade;

    //@OneToMany(targetEntity = Endereco.class, mappedBy = "codBairro")
    //private List<Endereco> enderecoCollection;

    public Bairro() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Cidade getCidade() {
        return this.cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    /*public List<Endereco> getEnderecoCollection() {
        return this.enderecoCollection;
    }
    

    public void setEnderecoCollection(List<Endereco> enderecoCollection) {
        this.enderecoCollection = enderecoCollection;
    }*/
}
