//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "cidade")
public class Cidade implements Serializable {

    @Column(name = "codigo", table = "cidade", nullable = false)
    @Id
    private Integer codigo;

    @Column(name = "nome", table = "cidade", nullable = false, length = 50)
    @Basic
    private String nome;

    @ManyToOne(targetEntity = Estado.class)
    @JoinColumn(name = "cod_estado")
    private Estado estado;

    @OneToMany(targetEntity = Bairro.class, mappedBy = "cidade")
    private List<Bairro> bairroCollection;

    public Cidade() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public List<Bairro> getBairroCollection() {
        return this.bairroCollection;
    }

    public void setBairroCollection(List<Bairro> bairroCollection) {
        this.bairroCollection = bairroCollection;
    }
}
