//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "empresa")
@PrimaryKeyJoinColumn(name="cod_pessoa")
public class Empresa extends Pessoa implements Serializable {

    /*@Column(name = "cod_pessoa", table = "empresa", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("codPessoa")
    private Integer codPessoa;*/

    @Column(name = "coordenada_x", table = "empresa")
    @Basic
    @FormParam("coordenadaX")
    private Integer coordenadaX;

    @Column(name = "coordenada_y", table = "empresa")
    @Basic
    @FormParam("coordenadaY")
    private Integer coordenadaY;

    @Column(name = "cod_endereco", table = "empresa")
    @Basic
    @FormParam("codEndereco")
    private Integer codEndereco;

    @OneToMany(targetEntity = EnderecoEmpresa.class, mappedBy = "empresa")
    private List<EnderecoEmpresa> enderecoEmpresaCollection;

    @OneToMany(targetEntity = TabelaPreco.class, mappedBy = "empresa")
    private List<TabelaPreco> tabelaPrecoCollection;

    public Empresa() {

    }

    public Integer getCoordenadaX() {
        return this.coordenadaX;
    }

    public void setCoordenadaX(Integer coordenadaX) {
        this.coordenadaX = coordenadaX;
    }

    public Integer getCoordenadaY() {
        return this.coordenadaY;
    }

    public void setCoordenadaY(Integer coordenadaY) {
        this.coordenadaY = coordenadaY;
    }

    public Integer getCodEndereco() {
        return this.codEndereco;
    }

    public void setCodEndereco(Integer codEndereco) {
        this.codEndereco = codEndereco;
    }

    public List<EnderecoEmpresa> getEnderecoEmpresaCollection() {
        return this.enderecoEmpresaCollection;
    }

    public void setEnderecoEmpresaCollection(List<EnderecoEmpresa> enderecoEmpresaCollection) {
        this.enderecoEmpresaCollection = enderecoEmpresaCollection;
    }

    public List<TabelaPreco> getTabelaPrecoCollection() {
        return this.tabelaPrecoCollection;
    }

    public void setTabelaPrecoCollection(List<TabelaPreco> tabelaPrecoCollection) {
        this.tabelaPrecoCollection = tabelaPrecoCollection;
    }
}
