//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

@Entity
@Table(name = "empresa")
@PrimaryKeyJoinColumn(name="cod_pessoa")
public class Empresa extends Pessoa implements Serializable {

    @Column(name = "latitude", table = "empresa", precision=13, scale=10)
    private BigDecimal latitude;

    @Column(name = "longitude", table = "empresa", precision=13, scale=10)
    private BigDecimal longitude;

    @ManyToOne(targetEntity = Endereco.class)
    @JoinColumn(name = "cod_endereco")
    private Endereco endereco;

    @OneToMany(targetEntity = EnderecoEmpresa.class, mappedBy = "empresa")
    private List<EnderecoEmpresa> enderecoEmpresaCollection;

    @OneToMany(targetEntity = TabelaPreco.class, mappedBy = "empresa")
    private List<TabelaPreco> tabelaPrecoCollection;

    public Empresa() {

    }

    public BigDecimal  getLatitude() {
        return this.latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public BigDecimal getLongitude() {
        return this.longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    public List<EnderecoEmpresa> getEnderecoEmpresaCollection() {
        return this.enderecoEmpresaCollection;
    }

    public void setEnderecoEmpresaCollection(List<EnderecoEmpresa> enderecoEmpresaCollection) {
        this.enderecoEmpresaCollection = enderecoEmpresaCollection;
    }

    public List<TabelaPreco> getTabelaPrecoCollection() {
        return this.tabelaPrecoCollection;
    }

    public void setTabelaPrecoCollection(List<TabelaPreco> tabelaPrecoCollection) {
        this.tabelaPrecoCollection = tabelaPrecoCollection;
    }
}
