//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.Objects;

public class EnderecoEmpresaPK implements Serializable {

    private int codEmpresa;

    private int codEndereco;

    public EnderecoEmpresaPK() {

    }

    public int getCodEmpresa() {
        return this.codEmpresa;
    }

    public void setCodEmpresa(int codEmpresa) {
        this.codEmpresa = codEmpresa;
    }

    public int getCodEndereco() {
        return this.codEndereco;
    }

    public void setCodEndereco(int codEndereco) {
        this.codEndereco = codEndereco;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.codEmpresa;
        hash = 59 * hash + this.codEndereco;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EnderecoEmpresaPK other = (EnderecoEmpresaPK) obj;
        if (this.codEmpresa != other.codEmpresa) {
            return false;
        }
        if (this.codEndereco != other.codEndereco) {
            return false;
        }
        return true;
    }

}
