//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "endereco_empresa")
public class EnderecoEmpresa implements Serializable {

    @Column(name = "cod_empresa", table = "endereco_empresa", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @FormParam("codEmpresa")
    private int codEmpresa;

    @Column(name = "cod_endereco", table = "endereco_empresa", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @FormParam("codEndereco")
    private int codEndereco;

    @Column(name = "numero", table = "endereco_empresa", unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    @FormParam("numero")
    private Integer numero;

    @ManyToOne(optional = false, targetEntity = Empresa.class)
    @JoinColumn(name = "cod_empresa", insertable = false, nullable = true, unique = false, updatable = false)
    private Empresa empresa;

    @ManyToOne(optional = false, targetEntity = Endereco.class)
    @JoinColumn(name = "cod_endereco", insertable = false, nullable = true, unique = false, updatable = false)
    private Endereco endereco;

    public EnderecoEmpresa() {

    }

    public int getCodEmpresa() {
        return this.codEmpresa;
    }

    public void setCodEmpresa(int codEmpresa) {
        this.codEmpresa = codEmpresa;
    }

    public int getCodEndereco() {
        return this.codEndereco;
    }

    public void setCodEndereco(int codEndereco) {
        this.codEndereco = codEndereco;
    }

    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
}
