//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "endereco")
public class Endereco implements Serializable {

    @Column(name = "codigo", table = "endereco", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("codigo")
    private Integer codigo;

    @Column(name = "logradouro", table = "endereco", unique = false, updatable = true, insertable = true, nullable = true, length = 100, scale = 0, precision = 0)
    @Basic
    @FormParam("logradouro")
    private String logradouro;

    @Column(name = "cep", table = "endereco", unique = false, updatable = true, insertable = true, nullable = true, length = 8, scale = 0, precision = 0)
    @Basic
    @FormParam("cep")
    private String cep;

    @ManyToOne(optional = true, targetEntity = Bairro.class)
    @JoinColumn(name = "cod_bairro", insertable = true, nullable = true, unique = false, updatable = true)
    private Bairro codBairro;

    @OneToMany(targetEntity = EnderecoEmpresa.class, mappedBy = "endereco")
    private List<EnderecoEmpresa> enderecoEmpresaCollection;

    public Endereco() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public Bairro getCodBairro() {
        return this.codBairro;
    }

    public void setCodBairro(Bairro codBairro) {
        this.codBairro = codBairro;
    }

    public List<EnderecoEmpresa> getEnderecoEmpresaCollection() {
        return this.enderecoEmpresaCollection;
    }

    public void setEnderecoEmpresaCollection(List<EnderecoEmpresa> enderecoEmpresaCollection) {
        this.enderecoEmpresaCollection = enderecoEmpresaCollection;
    }
}
