//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "estado")
public class Estado implements Serializable {

    @Column(name = "codigo", table = "estado", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @FormParam("codigo")
    private Integer codigo;

    @Column(name = "nome", table = "estado", unique = false, updatable = true, insertable = true, nullable = true, length = 30, scale = 0, precision = 0)
    @Basic
    @FormParam("nome")
    private String nome;

    @OneToMany(targetEntity = Cidade.class, mappedBy = "codEstado")
    private List<Cidade> cidadeCollection;

    public Estado() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public List<Cidade> getCidadeCollection() {
        return this.cidadeCollection;
    }

    public void setCidadeCollection(List<Cidade> cidadeCollection) {
        this.cidadeCollection = cidadeCollection;
    }
}
