//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "estado", uniqueConstraints = @UniqueConstraint(columnNames = {"sigla"}))
public class Estado implements Serializable {

    @Column(name = "codigo", table = "estado", nullable = false)
    @Id
    @FormParam("codigo")
    private Integer codigo;

    @Column(name = "nome", table = "estado", length = 30, nullable = false)
    @Basic
    @FormParam("nome")
    private String nome;
    
    @Column(name = "sigla", table = "estado", nullable = false, length = 2, columnDefinition = "bpchar")
    @Basic
    @FormParam("sigla")
    private String sigla;

    @OneToMany(targetEntity = Cidade.class, mappedBy = "estado")
    private List<Cidade> cidadeCollection;

    public Estado() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
    
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public List<Cidade> getCidadeCollection() {
        return this.cidadeCollection;
    }

    public void setCidadeCollection(List<Cidade> cidadeCollection) {
        this.cidadeCollection = cidadeCollection;
    }
}
