//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import br.com.mobitec.buscabarato.validacao.DeleteRestrict;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "marca")
public class Marca implements Serializable {
    
    @Id
    @SequenceGenerator(name="marca_codigo_seq", sequenceName="marca_codigo_seq", allocationSize = 1)
    @GeneratedValue(generator="marca_codigo_seq", strategy=GenerationType.SEQUENCE)
    private Integer codigo;
    
    @Column(length = 50)
    @Basic
    @NotNull(message = "O nome da marca não pode ficar vazio")
    private String nome;

    
    //@ManyToMany(targetEntity = Produto.class, mappedBy = "marcas")
    @ManyToMany()
    @JoinTable(name = "marca_produto", joinColumns = {
        @JoinColumn(name = "cod_marca", table = "marca_produto")}, inverseJoinColumns = {
        @JoinColumn(name = "cod_produto", table = "marca_produto")})
    @DeleteRestrict(message = "Esta marca possui produtos relacionados")
    private List<Produto> produtos;

    public Marca() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public List<Produto> getProdutos() {
        return this.produtos;
    }

    public void setProdutos(List<Produto> produtos) {
        this.produtos = produtos;
    }
}
