//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "produto")
public class Produto implements Serializable {

    @Column(name = "codigo", table = "produto", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer codigo;

    @Column(name = "descricao", table = "produto", nullable = false, length = 80)
    @Basic
    private String descricao;

    @ManyToMany(targetEntity = Marca.class)
    @JoinTable(name = "marca_produto", joinColumns = {
        @JoinColumn(name = "cod_marca", table = "marca_produto")}, inverseJoinColumns = {
        @JoinColumn(name = "cod_produto", table = "marca_produto")})
    private List<Marca> marcas;

    @ManyToOne(targetEntity = TipoProduto.class)
    @JoinColumn(name = "cod_tipo_produto")
    private TipoProduto TipoProduto;

    @OneToMany(targetEntity = TabelaPreco.class, mappedBy = "produto")
    private List<TabelaPreco> tabelaPrecoCollection;

    public Produto() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<Marca> getMarcas() {
        return this.marcas;
    }

    public void setMarcas(List<Marca> marcas) {
        this.marcas = marcas;
    }

    public TipoProduto getTipoProduto() {
        return this.TipoProduto;
    }

    public void setTipoProduto(TipoProduto TipoProduto) {
        this.TipoProduto = TipoProduto;
    }

    public List<TabelaPreco> getTabelaPrecoCollection() {
        return this.tabelaPrecoCollection;
    }

    public void setTabelaPrecoCollection(List<TabelaPreco> tabelaPrecoCollection) {
        this.tabelaPrecoCollection = tabelaPrecoCollection;
    }
}
