//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

@Entity
@Table(name = "produto")
public class Produto implements Serializable {

    @Column(name = "codigo", table = "produto", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("codigo")
    private Integer codigo;

    @Column(name = "descricao", table = "produto", nullable = false, length = 80)
    @Basic
    @FormParam("descricao")
    private String descricao;

    @OneToMany(targetEntity = TabelaPreco.class, mappedBy = "produto")
    private List<TabelaPreco> tabelaPrecoCollection;

    public Produto() {

    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<TabelaPreco> getTabelaPrecoCollection() {
        return this.tabelaPrecoCollection;
    }

    public void setTabelaPrecoCollection(List<TabelaPreco> tabelaPrecoCollection) {
        this.tabelaPrecoCollection = tabelaPrecoCollection;
    }
}
