//
// This file was generated by the JPA Modeler
//
package br.com.mobitec.buscabarato.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.constraints.Min;

@Entity
@Table(name = "usuario")
@PrimaryKeyJoinColumn(name="cod_pessoa")
public class Usuario extends Pessoa implements Serializable {

    @Column(name = "ponto", table = "usuario", nullable = false)
    @Basic
    @Min(value = 0, message = "A quantidade de pondos n�o pode ser menor que zero")
    private int ponto;

    public Usuario() {

    }

    public int getPonto() {
        return this.ponto;
    }

    public void setPonto(int ponto) {
        this.ponto = ponto;
    }
}
